/*
    id: 1,
    name: 'High-Quality MASS PROTEIN',
    description: 'Fórmula de alta pureza con 28g de proteína de máxima pureza con fórmula mejorada',
    originalPrice: 63.45,
    offerPrice: 34.9,
    discount: 45,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.7,
    reviews: 348,
    badge: 'EXCLUSIVO',
    marca: 'Ronnie Coleman',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'high-quality-mass-protein',
    cantidad: 145,
    stock: [
      [
        { sabor: 'Chocolate', tamano: '500g', cantidad: 25 },
        { sabor: 'Chocolate', tamano: '1kg', cantidad: 30 },
        { sabor: 'Chocolate', tamano: '2kg', cantidad: 20 },
        { sabor: 'Chocolate', tamano: '5kg', cantidad: 10 },
      ],
      [
        { sabor: 'Vainilla', tamano: '500g', cantidad: 15 },
        { sabor: 'Vainilla', tamano: '1kg', cantidad: 20 },
        { sabor: 'Vainilla', tamano: '2kg', cantidad: 10 },
        { sabor: 'Vainilla', tamano: '5kg', cantidad: 5 },
      ],
      [
        { sabor: 'Fresa', tamano: '500g', cantidad: 12 },
        { sabor: 'Fresa', tamano: '1kg', cantidad: 18 },
        { sabor: 'Fresa', tamano: '2kg', cantidad: 7 },
        { sabor: 'Fresa', tamano: '5kg', cantidad: 3 },
      ],
      [
        { sabor: 'Cookies & Cream', tamano: '500g', cantidad: 0 },
        { sabor: 'Cookies & Cream', tamano: '1kg', cantidad: 2 },
        { sabor: 'Cookies & Cream', tamano: '2kg', cantidad: 0 },
        { sabor: 'Cookies & Cream', tamano: '5kg', cantidad: 0 },
      ],
      [
        { sabor: 'Plátano', tamano: '500g', cantidad: 10 },
        { sabor: 'Plátano', tamano: '1kg', cantidad: 15 },
        { sabor: 'Plátano', tamano: '2kg', cantidad: 8 },
        { sabor: 'Plátano', tamano: '5kg', cantidad: 2 }
      ],
    ],
    //El primer parametro de carracteristicas no es la lista como tal, es lo q tiene q consumir, para el mensaje de arriba (Información nutricional (por servicio de 30g) ese)
    carracteristicas: ['30g', 'tal', 'tal2', 'tal3', 'tal4', 'tal5', 'tal6'],
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (contiene emulsionante: lecitina de soja), aislado de proteína de suero de leche (90%), cacao en polvo (10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: ['Tomar 1-3 veces al día, según necesidades proteicas', 'Ideal después del entrenamiento para maximizar la recuperación', 'Puede tomarse entre comidas como snack proteico', 'Conservar en lugar fresco y seco'],
    informacionNutricional: {
      porcion: '30g',
      calorias: '120 kcal',
      proteinas: '24g',
      carbohidratos: '3g',
      azucares: '1.5g',
      grasas: '1.8g',
      grasasSaturadas: '1.1g',
      fibra: '0.6g',
      sal: '0.25g',
      sodio: '100mg',
      calcio: '140mg',
      hierro: '1.2mg',
      vitaminaD: '0.75µg',
      vitaminaB12: '1.1µg',
      enzimasDigestivas: '25mg',
      aminoacidos: {
        leucina: '2.5g',
        isoleucina: '1.5g',
        valina: '1.6g',
        glutamina: '4.8g'
      }
    }
*/


export const allProducts = [
  {
    id: 1,
    name: 'High-Quality MASS PROTEIN',
    description: 'Fórmula de alta pureza con 28g de proteína de máxima pureza con fórmula mejorada',
    originalPrice: 63.45,
    offerPrice: 34.9,
    discount: 45,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.7,
    reviews: 348,
    badge: 'EXCLUSIVO',
    marca: 'Ronnie Coleman',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'high-quality-mass-protein',
    cantidad: 145,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (contiene emulsionante: lecitina de soja), aislado de proteína de suero de leche (90%), cacao en polvo (10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 2,
    name: 'Premium PROTEIN FORMULA',
    description: 'Fórmula de alta pureza con 27g de proteína pura por dosis y absorción rápida',
    originalPrice: 31.86,
    offerPrice: 21.66,
    discount: 32,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.3,
    reviews: 212,
    badge: 'DESTACADO',
    marca: 'Allmax',
    tipo: 'Casein Protein',
    colesterol: 'Sin colesterol',
    slug: 'premium-protein-formula',
    cantidad: 170,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (contiene emulsionante: lecitina de soja), aislado de proteína de suero de leche (85%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 3,
    name: 'Maximum STRENGTH NUTRITION',
    description: 'Proteína de absorción rápida con 26g de proteína de suero aislada para deportistas exigentes',
    originalPrice: 52.8,
    offerPrice: 44.35,
    discount: 16,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.7,
    reviews: 112,
    badge: 'POPULAR',
    marca: 'ProSupps',
    tipo: 'Whey Protein',
    colesterol: 'Mínimo',
    slug: 'maximum-strength-nutrition',
    cantidad: 47,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (92%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 4,
    name: 'Extreme PROTEIN COMPLEX',
    description: 'Nutrición deportiva de élite con 29g de proteína por medida para una recuperación óptima',
    originalPrice: 40.61,
    offerPrice: 40.61,
    discount: 0,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 3.9,
    reviews: 125,
    badge: 'RECOMENDADO',
    marca: 'BSN',
    tipo: 'Casein Protein',
    colesterol: 'Mínimo',
    slug: 'extreme-protein-complex',
    cantidad: 135,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (85%), concentrado de proteína de suero de leche (10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 5,
    name: 'Advanced WHEY POWER',
    description: 'Fórmula de alta pureza con 20g de proteína de absorción rápida con fórmula mejorada',
    originalPrice: 72.7,
    offerPrice: 33.44,
    discount: 54,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 5,
    reviews: 421,
    badge: 'RECOMENDADO',
    marca: 'Nutrex',
    tipo: 'Blend Protein',
    colesterol: 'Reducido',
    slug: 'advanced-whey-power',
    cantidad: 81,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, caseína micelar), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 6,
    name: 'Premium WHEY RECOVERY',
    description: 'Mezcla de proteínas que ofrece 25g de proteína por porción con fórmula mejorada',
    originalPrice: 63.96,
    offerPrice: 32.62,
    discount: 49,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.5,
    reviews: 495,
    badge: 'EXCLUSIVO',
    marca: 'Rule One',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'premium-whey-recovery',
    cantidad: 147,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (60%), proteína de arroz (25%), proteína de cáñamo (10%), aromas naturales, espesantes (goma xantana, goma guar), edulcorantes naturales (stevia), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 7,
    name: 'Ultra PROTEIN ISOLATE',
    description: 'Aislado de proteína de suero con 30g de proteína por servicio y mínimo contenido de grasa',
    originalPrice: 69.99,
    offerPrice: 49.99,
    discount: 29,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.8,
    reviews: 356,
    badge: 'TOP VENTAS',
    marca: 'Optimum Nutrition',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'ultra-protein-isolate',
    cantidad: 120,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 8,
    name: 'Pro MUSCLE BUILDER',
    description: 'Fórmula avanzada con 28g de proteína y aminoácidos adicionales para maximizar el crecimiento muscular',
    originalPrice: 59.99,
    offerPrice: 39.99,
    discount: 33,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.6,
    reviews: 289,
    badge: 'DESTACADO',
    marca: 'Dymatize',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    superOfertas: true,
    slug: 'pro-muscle-builder',
    cantidad: 95,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, caseína micelar), L-Glutamina (5g), BCAA (5g), creatina monohidrato (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 9,
    name: 'Elite PERFORMANCE PROTEIN',
    description: 'Proteína premium con 25g por servicio y digestión optimizada para atletas de alto rendimiento',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.9,
    reviews: 412,
    badge: 'PREMIUM',
    marca: 'MuscleTech',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'elite-performance-protein',
    cantidad: 110,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (90%), aislado de proteína de suero de leche (5%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 10,
    name: 'Natural PLANT PROTEIN',
    description: 'Proteína vegetal con 22g por servicio, sin aditivos artificiales y fácil digestión',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.4,
    reviews: 278,
    badge: 'VEGANO',
    marca: 'Vega',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'natural-plant-protein',
    cantidad: 85,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (50%), proteína de arroz (30%), proteína de cáñamo (15%), proteína de semilla de calabaza (5%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 11,
    name: 'Power MASS GAINER',
    description: 'Ganador de peso con 1200 calorías y 50g de proteína por servicio para aumento de masa muscular',
    originalPrice: 79.99,
    offerPrice: 59.99,
    discount: 25,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.5,
    reviews: 320,
    badge: 'BESTSELLER',
    marca: 'Serious Mass',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'power-mass-gainer',
    cantidad: 75,
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (5g), glutamina (5g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 12,
    name: 'Lean PROTEIN MATRIX',
    description: 'Fórmula de proteína con 24g por servicio y L-carnitina para definición muscular',
    originalPrice: 45.99,
    offerPrice: 36.99,
    discount: 20,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.6,
    reviews: 245,
    badge: 'DEFINICIÓN',
    marca: 'Scitec Nutrition',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'lean-protein-matrix',
    cantidad: 90,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche), L-carnitina (1g), té verde (extracto), CLA (ácido linoleico conjugado), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 13,
    name: 'Iso WHEY ZERO',
    description: 'Aislado de proteína sin lactosa con 27g de proteína por servicio y cero azúcares añadidos',
    originalPrice: 57.99,
    offerPrice: 42.99,
    discount: 26,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.7,
    reviews: 310,
    badge: 'SIN LACTOSA',
    marca: 'BioTech USA',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'iso-whey-zero',
    cantidad: 105,
    informacionAlergenos: 'Contiene soja. Sin lactosa. Fabricado en instalaciones que también procesan leche, huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%, sin lactosa), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche sin lactosa. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 14,
    name: 'Night TIME PROTEIN',
    description: 'Proteína de liberación lenta con 25g por servicio, ideal para tomar antes de dormir',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.5,
    reviews: 265,
    badge: 'NOCTURNO',
    marca: 'Universal Nutrition',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'night-time-protein',
    cantidad: 95,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (90%), concentrado de proteína de suero de leche (5%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.'
  },
  {
    id: 15,
    name: 'Complete PROTEIN BLEND',
    description: 'Mezcla completa de proteínas con 24g por servicio y digestión escalonada para máxima eficacia',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.6,
    reviews: 298,
    badge: 'COMPLETO',
    marca: 'MyProtein',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    superOfertas: true,
    slug: 'complete-protein-blend',
    cantidad: 110,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 40%, aislado de proteína de suero de leche 30%, caseína micelar 20%, proteína de huevo 10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 16,
    name: 'Hydro WHEY PROTEIN',
    description: 'Proteína de suero hidrolizada con 28g por servicio y absorción ultra rápida',
    originalPrice: 64.99,
    offerPrice: 49.99,
    discount: 23,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.8,
    reviews: 342,
    badge: 'PREMIUM',
    marca: 'Optimum Nutrition',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'hydro-whey-protein',
    cantidad: 85,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 17,
    name: 'Organic PLANT PROTEIN',
    description: 'Proteína vegetal orgánica con 21g por servicio y mezcla de superalimentos',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.4,
    reviews: 256,
    badge: 'ORGÁNICO',
    marca: 'Garden of Life',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'organic-plant-protein',
    cantidad: 75,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones certificadas para productos orgánicos.',
    infoIngredientes: 'Proteína de guisante orgánica (40%), proteína de arroz integral orgánico (30%), proteína de semillas de chía orgánica (10%), proteína de semillas de calabaza orgánica (10%), mezcla de superalimentos orgánicos (espirulina, maca, cúrcuma, jengibre), aromas naturales, stevia orgánica, sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 18,
    name: 'Whey PROTEIN ISOLATE',
    description: 'Aislado de proteína de suero con 29g por servicio y mínimo contenido de carbohidratos y grasas',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.7,
    reviews: 325,
    badge: 'BESTSELLER',
    marca: 'Isopure',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'whey-protein-isolate',
    cantidad: 120,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (97%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 19,
    name: 'Pro CASEIN PROTEIN',
    description: 'Caseína micelar con 25g de proteína por servicio y liberación prolongada durante 8 horas',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.5,
    reviews: 275,
    badge: 'NOCTURNO',
    marca: 'Dymatize',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'pro-casein-protein',
    cantidad: 90,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.'
  },
  {
    id: 20,
    name: 'Lean WHEY PROTEIN',
    description: 'Proteína de suero con 23g por servicio y L-carnitina para apoyo en la definición muscular',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.4,
    reviews: 245,
    badge: 'DEFINICIÓN',
    marca: 'Scitec Nutrition',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'lean-whey-protein',
    cantidad: 85,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (85%), L-carnitina (1g), extracto de té verde, CLA (ácido linoleico conjugado), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 21,
    name: 'Ultra MASS GAINER',
    description: 'Ganador de peso con 1000 calorías y 45g de proteína por servicio para aumento de masa muscular',
    originalPrice: 69.99,
    offerPrice: 54.99,
    discount: 21,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.3,
    reviews: 230,
    badge: 'VOLUMEN',
    marca: 'Mass Tech',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'ultra-mass-gainer',
    cantidad: 70,
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (3g), glutamina (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 22,
    name: 'Premium WHEY CONCENTRATE',
    description: 'Concentrado de proteína de suero con 22g por servicio y excelente relación calidad-precio',
    originalPrice: 39.99,
    offerPrice: 29.99,
    discount: 25,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.2,
    reviews: 320,
    badge: 'ECONÓMICO',
    marca: 'MyProtein',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'premium-whey-concentrate',
    cantidad: 150,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (80%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 23,
    name: 'Vegan PROTEIN COMPLETE',
    description: 'Proteína vegetal completa con 20g por servicio y perfil completo de aminoácidos',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.3,
    reviews: 210,
    badge: 'VEGANO',
    marca: 'Sunwarrior',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    superOfertas: true,
    slug: 'vegan-protein-complete',
    cantidad: 80,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (40%), proteína de arroz integral (30%), proteína de semillas de calabaza (15%), proteína de cáñamo (10%), mezcla de aminoácidos esenciales (5%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 24,
    name: 'Gold STANDARD WHEY',
    description: 'Proteína de suero premium con 24g por servicio y mezcla de concentrado, aislado e hidrolizado',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.8,
    reviews: 520,
    badge: 'TOP VENTAS',
    marca: 'Optimum Nutrition',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'gold-standard-whey',
    cantidad: 200,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 70%, aislado de proteína de suero de leche 20%, proteína de suero hidrolizada 10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 25,
    name: 'Combat PROTEIN POWDER',
    description: 'Proteína de liberación en 5 fases con 25g por servicio para nutrición prolongada',
    originalPrice: 56.99,
    offerPrice: 45.99,
    discount: 19,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.6,
    reviews: 310,
    badge: 'PREMIUM',
    marca: 'MusclePharm',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'combat-protein-powder',
    cantidad: 120,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas de 5 fases (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, proteína de suero hidrolizada, caseína micelar, proteína de clara de huevo), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 26,
    name: 'Nitro TECH PROTEIN',
    description: 'Fórmula avanzada con 30g de proteína por servicio y creatina para máximo rendimiento',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.7,
    reviews: 340,
    badge: 'RENDIMIENTO',
    marca: 'MuscleTech',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'nitro-tech-protein',
    cantidad: 110,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (70%), concentrado de proteína de suero de leche (20%), creatina monohidrato (3g), L-glutamina (2g), BCAA (2g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 27,
    name: 'Syntha-6 PROTEIN MATRIX',
    description: 'Mezcla de proteínas de liberación sostenida con 22g por servicio y delicioso sabor cremoso',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.5,
    reviews: 290,
    badge: 'SABOR PREMIUM',
    marca: 'BSN',
    tipo: 'Blend Protein',
    colesterol: 'Moderado',
    slug: 'syntha-6-protein-matrix',
    cantidad: 100,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, caseína micelar, proteína de leche, proteína de clara de huevo, proteína de suero hidrolizada), MCT (triglicéridos de cadena media), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 28,
    name: 'Serious MASS GAINER',
    description: 'Ganador de peso con 1250 calorías y 50g de proteína por servicio para aumento de masa muscular',
    originalPrice: 74.99,
    offerPrice: 59.99,
    discount: 20,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.4,
    reviews: 280,
    badge: 'VOLUMEN',
    marca: 'Optimum Nutrition',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'serious-mass-gainer',
    cantidad: 80,
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (5g), glutamina (5g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 29,
    name: 'Iso 100 HYDROLYZED',
    description: 'Proteína de suero hidrolizada con 25g por servicio y cero carbohidratos y grasas',
    originalPrice: 64.99,
    offerPrice: 51.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.8,
    reviews: 330,
    badge: 'PREMIUM',
    marca: 'Dymatize',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'iso-100-hydrolyzed',
    cantidad: 90,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (100%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 30,
    name: 'Pure WHEY ISOLATE',
    description: 'Aislado de proteína de suero con 27g por servicio y mínimo contenido de lactosa',
    originalPrice: 57.99,
    offerPrice: 45.99,
    discount: 21,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.7,
    reviews: 315,
    badge: 'CALIDAD',
    marca: 'Reflex Nutrition',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'pure-whey-isolate',
    cantidad: 95,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 31,
    name: 'Micellar CASEIN PROTEIN',
    description: 'Caseína micelar pura con 24g de proteína por servicio y liberación lenta durante 8 horas',
    originalPrice: 54.99,
    offerPrice: 43.99,
    discount: 20,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.5,
    reviews: 260,
    badge: 'NOCTURNO',
    marca: 'Optimum Nutrition',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'micellar-casein-protein',
    cantidad: 85,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (98%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.'
  },
  {
    id: 32,
    name: 'Egg WHITE PROTEIN',
    description: 'Proteína de clara de huevo con 24g por servicio, baja en grasas y de alta calidad biológica',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.3,
    reviews: 220,
    badge: 'NATURAL',
    marca: 'NOW Sports',
    tipo: 'Egg Protein',
    colesterol: 'Mínimo',
    slug: 'egg-white-protein',
    cantidad: 75,
    informacionAlergenos: 'Contiene huevo. Fabricado en instalaciones que también procesan leche, soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de clara de huevo en polvo (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 33,
    name: 'Beef PROTEIN ISOLATE',
    description: 'Proteína aislada de carne de vacuno con 25g por servicio, sin lactosa ni gluten',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.2,
    reviews: 185,
    badge: 'SIN LACTOSA',
    marca: 'MuscleMeds',
    tipo: 'Beef Protein',
    colesterol: 'Bajo',
    slug: 'beef-protein-isolate',
    cantidad: 70,
    informacionAlergenos: 'No contiene lactosa ni gluten. Fabricado en instalaciones que también procesan soja, huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de carne de vacuno (90%), creatina monohidrato (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 34,
    name: 'Slim DIET PROTEIN',
    description: 'Proteína para control de peso con 20g por servicio y extractos de plantas para apoyo metabólico',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.1,
    reviews: 195,
    badge: 'CONTROL PESO',
    marca: 'PhD Nutrition',
    tipo: 'Diet Protein',
    colesterol: 'Bajo',
    slug: 'slim-diet-protein',
    cantidad: 80,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, caseína micelar), L-carnitina (1g), extracto de té verde, extracto de garcinia cambogia, extracto de café verde, fibra de avena, aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 35,
    name: 'Tri-Blend PROTEIN',
    description: 'Mezcla de tres proteínas con 23g por servicio y liberación en tres fases para nutrición continua',
    originalPrice: 51.99,
    offerPrice: 41.99,
    discount: 19,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.5,
    reviews: 275,
    badge: 'COMPLETO',
    marca: 'MyProtein',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'tri-blend-protein',
    cantidad: 105,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 40%, aislado de proteína de suero de leche 30%, caseína micelar 30%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 36,
    name: 'Whey PROTEIN CONCENTRATE',
    description: 'Concentrado de proteína de suero con 22g por servicio y excelente relación calidad-precio',
    originalPrice: 42.99,
    offerPrice: 32.99,
    discount: 23,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4.2,
    reviews: 310,
    badge: 'ECONÓMICO',
    marca: 'Bulk Powders',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'whey-protein-concentrate',
    cantidad: 140,
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (80%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 37,
    name: 'Pea PROTEIN ISOLATE',
    description: 'Proteína aislada de guisante con 24g por servicio, vegana y de fácil digestión',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.3,
    reviews: 230,
    badge: 'VEGANO',
    marca: 'Bulk Powders',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'pea-protein-isolate',
    cantidad: 85,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de guisante (90%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 38,
    name: 'Rice PROTEIN ISOLATE',
    description: 'Proteína aislada de arroz con 22g por servicio, vegana y sin alérgenos comunes',
    originalPrice: 45.99,
    offerPrice: 36.99,
    discount: 20,
    image: [ '/ofertaDelDia2.webp' ],
    rating: 4.1,
    reviews: 190,
    badge: 'VEGANO',
    marca: 'Sunwarrior',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'rice-protein-isolate',
    cantidad: 75,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de arroz integral (95%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 39,
    name: 'Hemp PROTEIN POWDER',
    description: 'Proteína de cáñamo con 18g por servicio, rica en ácidos grasos esenciales y fibra',
    originalPrice: 43.99,
    offerPrice: 34.99,
    discount: 20,
    image: [ '/ofertaDelDia1.webp' ],
    rating: 4,
    reviews: 165,
    badge: 'NATURAL',
    marca: 'Manitoba Harvest',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    superOfertas: true,
    slug: 'hemp-protein-powder',
    cantidad: 65,
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de semillas de cáñamo (100%), sin aditivos ni conservantes.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  },
  {
    id: 40,
    name: 'Soy PROTEIN ISOLATE',
    description: 'Proteína aislada de soja con 25g por servicio, vegana y con perfil completo de aminoácidos',
    originalPrice: 44.99,
    offerPrice: 35.99,
    discount: 20,
    image: [ '/ofertaDelDia3.webp' ],
    rating: 4.2,
    reviews: 210,
    badge: 'VEGANO',
    marca: 'NOW Sports',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'soy-protein-isolate',
    cantidad: 90,
    informacionAlergenos: 'Contiene soja. Apto para veganos. Fabricado en instalaciones que también procesan leche, huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de soja (95%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.'
  }
]
export const productosSuperOfertas = allProducts.filter(producto => producto.superOfertas);