/*
    stock: [
      [
        { sabor: 'Chocolate', tamano: '500g', cantidad: 25 },
        { sabor: 'Chocolate', tamano: '1kg', cantidad: 30 },
        { sabor: 'Chocolate', tamano: '2kg', cantidad: 20 },
        { sabor: 'Chocolate', tamano: '5kg', cantidad: 10 },
      ],
      [
        { sabor: 'Vainilla', tamano: '500g', cantidad: 15 },
        { sabor: 'Vainilla', tamano: '1kg', cantidad: 20 },
        { sabor: 'Vainilla', tamano: '2kg', cantidad: 10 },
        { sabor: 'Vainilla', tamano: '5kg', cantidad: 5 },
      ],
      [
        { sabor: 'Fresa', tamano: '500g', cantidad: 12 },
        { sabor: 'Fresa', tamano: '1kg', cantidad: 18 },
        { sabor: 'Fresa', tamano: '2kg', cantidad: 7 },
        { sabor: 'Fresa', tamano: '5kg', cantidad: 3 },
      ],
      [
        { sabor: 'Cookies & Cream', tamano: '500g', cantidad: 0 },
        { sabor: 'Cookies & Cream', tamano: '1kg', cantidad: 2 },
        { sabor: 'Cookies & Cream', tamano: '2kg', cantidad: 0 },
        { sabor: 'Cookies & Cream', tamano: '5kg', cantidad: 0 },
      ],
      [
        { sabor: 'Plátano', tamano: '500g', cantidad: 10 },
        { sabor: 'Plátano', tamano: '1kg', cantidad: 15 },
        { sabor: 'Plátano', tamano: '2kg', cantidad: 8 },
        { sabor: 'Plátano', tamano: '5kg', cantidad: 2 }
      ],
    ],
    
    informacionNutricional: {
      porcion: '30g',
      calorias: '120 kcal',
      proteinas: '24g',
      carbohidratos: '3g',
      azucares: '1.5g',
      grasas: '1.8g',
      grasasSaturadas: '1.1g',
      fibra: '0.6g',
      sal: '0.25g',
      sodio: '100mg',
      calcio: '140mg',
      hierro: '1.2mg',
      vitaminaD: '0.75µg',
      vitaminaB12: '1.1µg',
      enzimasDigestivas: '25mg',
      aminoacidos: 'leucina: 2.5g;isoleucina: 1.5g;valina: 1.6g;glutamina: 4.8g'
    }
*/

export const allProducts = [
  {
    id: 1,
    name: 'High-Quality MASS PROTEIN',
    description: 'Fórmula de alta pureza con 28g de proteína de máxima pureza con fórmula mejorada',
    originalPrice: 63.45,
    offerPrice: 21.66,
    discount: 32,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp<<</ofertaDelDia2.webp',
    rating: 3.3,
    reviews: 348,
    badge: 'EXCLUSIVO',
    marca: 'Ronnie Coleman',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'high-quality-mass-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (contiene emulsionante: lecitina de soja), aislado de proteína de suero de leche (90%), cacao en polvo (10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Chocolate<<<Vainilla<<<Fresa',  
    categoriaEspecial: 'veganas<<<OfertaDelDia'
  },
  {
    id: 2,
    name: 'Premium PROTEIN FORMULA',
    description: 'Fórmula de alta pureza con 27g de proteína pura por dosis y absorción rápida',
    originalPrice: 31.86,
    image: '/ofertaDelDia2.webp',
    rating: 4.3,
    reviews: 212,
    badge: 'DESTACADO',
    marca: 'Allmax',
    tipo: 'Casein Protein',
    colesterol: 'Sin colesterol',
    slug: 'premium-protein-formula',
    informacionAlergenos: 'Contiene leche y sojasdasdasda. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de protedasasdasdadsadsasdadsasdasdína de suero de leche (contiene emulsionante: lecitina de soja), aislado de proteína de suero de leche (85%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Cookies & Cream<<<Plátano'
  },
  {
    id: 3,
    name: 'Maximum STRENGTH NUTRITION',
    description: 'Proteína de absorción rápida con 26g de proteína de suero aislada para deportistas exigentes',
    originalPrice: 52.8,
    offerPrice: 44.35,
    discount: 16,
    image: '/ofertaDelDia3.webp',
    rating: 4.7,
    reviews: 112,
    badge: 'POPULAR',
    marca: 'ProSupps',
    tipo: 'Whey Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'maximum-strength-nutrition',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (92%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Menta',
    categoriaEspecial: 'veganas<<<OfertaDelDia'
  },
  {
    id: 4,
    name: 'Extreme PROTEIN COMPLEX',
    description: 'Nutrición deportiva de élite con 29g de proteína por medida para una recuperación óptima',
    originalPrice: 40.61,
    image: '/ofertaDelDia2.webp',
    rating: 3.9,
    reviews: 125,
    badge: 'RECOMENDADO',
    marca: 'BSN',
    tipo: 'Casein Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'extreme-protein-complex',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (85%), concentrado de proteína de suero de leche (10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Caramelo',
    categoriaEspecial: 'veganas<<<OfertaDelDia'
  },
  {
    id: 5,
    name: 'Advanced WHEY POWER',
    description: 'Fórmula de alta pureza con 20g de proteína de absorción rápida con fórmula mejorada',
    originalPrice: 72.7,
    offerPrice: 33.44,
    discount: 54,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 5,
    reviews: 421,
    badge: 'RECOMENDADO',
    marca: 'Nutrex',
    tipo: 'Blend Protein',
    colesterol: 'Reducido',
    slug: 'advanced-whey-power',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, caseína micelar), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Café'
  },
  {
    id: 6,
    name: 'Premium WHEY RECOVERY',
    description: 'Mezcla de proteínas que ofrece 25g de proteína por porción con fórmula mejorada',
    originalPrice: 63.96,
    offerPrice: 32.62,
    discount: 49,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.5,
    reviews: 495,
    badge: 'EXCLUSIVO',
    marca: 'Rule One',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'premium-whey-recovery',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (60%), proteína de arroz (25%), proteína de cáñamo (10%), aromas naturales, espesantes (goma xantana, goma guar), edulcorantes naturales (stevia), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Limón'
  },
  {
    id: 7,
    name: 'Ultra PROTEIN ISOLATE',
    description: 'Aislado de proteína de suero con 30g de proteína por servicio y mínimo contenido de grasa',
    originalPrice: 69.99,
    offerPrice: 49.99,
    discount: 29,
    image: '/ofertaDelDia3.webp',
    rating: 4.8,
    reviews: 356,
    badge: 'TOP VENTAS',
    marca: 'Optimum Nutrition',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'ultra-protein-isolate',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Coco'
  },
  {
    id: 8,
    name: 'Pro MUSCLE BUILDER',
    description: 'Fórmula avanzada con 28g de proteína y aminoácidos adicionales para maximizar el crecimiento muscular',
    originalPrice: 59.99,
    offerPrice: 39.99,
    discount: 33,
    image: '/ofertaDelDia2.webp',
    rating: 4.6,
    reviews: 289,
    badge: 'DESTACADO',
    marca: 'Dymatize',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    superOfertas: true,
    slug: 'pro-muscle-builder',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, caseína micelar), L-Glutamina (5g), BCAA (5g), creatina monohidrato (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Pistacho',
    categoriaEspecial: 'veganas<<<OfertaDelDia'
  },
  {
    id: 9,
    name: 'Elite PERFORMANCE PROTEIN',
    description: 'Proteína premium con 25g por servicio y digestión optimizada para atletas de alto rendimiento',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.9,
    reviews: 412,
    badge: 'PREMIUM',
    marca: 'MuscleTech',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'elite-performance-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (90%), aislado de proteína de suero de leche (5%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Nuez'
  },
  {
    id: 10,
    name: 'Natural PLANT PROTEIN',
    description: 'Proteína vegetal con 22g por servicio, sin aditivos artificiales y fácil digestión',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: '/ofertaDelDia3.webp',
    rating: 4.4,
    reviews: 278,
    badge: 'VEGANO',
    marca: 'Vega',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'natural-plant-protein',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (50%), proteína de arroz (30%), proteína de cáñamo (15%), proteína de semilla de calabaza (5%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Dulce de Leche',
    categoriaEspecial: 'veganas<<<OfertaDelDia'
  },
  {
    id: 11,
    name: 'Power MASS GAINER',
    description: 'Ganador de peso con 1200 calorías y 50g de proteína por servicio para aumento de masa muscular',
    originalPrice: 79.99,
    offerPrice: 59.99,
    discount: 25,
    image: '/ofertaDelDia2.webp',
    rating: 4.5,
    reviews: 320,
    badge: 'BESTSELLER',
    marca: 'Serious Mass',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'power-mass-gainer',
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (5g), glutamina (5g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Mango'
  },
  {
    id: 12,
    name: 'Lean PROTEIN MATRIX',
    description: 'Fórmula de proteína con 24g por servicio y L-carnitina para definición muscular',
    originalPrice: 45.99,
    offerPrice: 36.99,
    discount: 20,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.6,
    reviews: 245,
    badge: 'DEFINICIÓN',
    marca: 'Scitec Nutrition',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'lean-protein-matrix',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, aislado de proteína de suero de leche), L-carnitina (1g), té verde (extracto), CLA (ácido linoleico conjugado), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Maracuyá'
  },
  {
    id: 13,
    name: 'Iso WHEY ZERO',
    description: 'Aislado de proteína sin lactosa con 27g de proteína por servicio y cero azúcares añadidos',
    originalPrice: 57.99,
    offerPrice: 42.99,
    discount: 26,
    image: '/ofertaDelDia3.webp',
    rating: 4.7,
    reviews: 310,
    badge: 'SIN LACTOSA',
    marca: 'BioTech USA',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'iso-whey-zero',
    informacionAlergenos: 'Contiene soja. Sin lactosa. Fabricado en instalaciones que también procesan leche, huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%, sin lactosa), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche sin lactosa. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Cereza'
  },
  {
    id: 14,
    name: 'Night TIME PROTEIN',
    description: 'Proteína de liberación lenta con 25g por servicio, ideal para tomar antes de dormir',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.5,
    reviews: 265,
    badge: 'NOCTURNO',
    marca: 'Universal Nutrition',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'night-time-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (90%), concentrado de proteína de suero de leche (5%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Avellana'
  },
  {
    id: 15,
    name: 'Complete PROTEIN BLEND',
    description: 'Mezcla completa de proteínas con 24g por servicio y digestión escalonada para máxima eficacia',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.6,
    reviews: 298,
    badge: 'COMPLETO',
    marca: 'MyProtein',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    superOfertas: true,
    slug: 'complete-protein-blend',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 40%, aislado de proteína de suero de leche 30%, caseína micelar 20%, proteína de huevo 10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Tiramisú'
  },
  {
    id: 16,
    name: 'Hydro WHEY PROTEIN',
    description: 'Proteína de suero hidrolizada con 28g por servicio y absorción ultra rápida',
    originalPrice: 64.99,
    offerPrice: 49.99,
    discount: 23,
    image: '/ofertaDelDia3.webp',
    rating: 4.8,
    reviews: 342,
    badge: 'PREMIUM',
    marca: 'Optimum Nutrition',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'hydro-whey-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Chicle'
  },
  {
    id: 17,
    name: 'Organic PLANT PROTEIN',
    description: 'Proteína vegetal orgánica con 21g por servicio y mezcla de superalimentos',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: '/ofertaDelDia2.webp',
    rating: 4.4,
    reviews: 256,
    badge: 'ORGÁNICO',
    marca: 'Garden of Life',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'organic-plant-protein',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones certificadas para productos orgánicos.',
    infoIngredientes: 'Proteína de guisante orgánica (40%), proteína de arroz integral orgánico (30%), proteína de semillas de chía orgánica (10%), proteína de semillas de calabaza orgánica (10%), mezcla de superalimentos orgánicos (espirulina, maca, cúrcuma, jengibre), aromas naturales, stevia orgánica, sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Sandía'
  },
  {
    id: 18,
    name: 'Whey PROTEIN ISOLATE',
    description: 'Aislado de proteína de suero con 29g por servicio y mínimo contenido de carbohidratos y grasas',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.7,
    reviews: 325,
    badge: 'BESTSELLER',
    marca: 'Isopure',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    slug: 'whey-protein-isolate',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (97%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Kiwi'
  },
  {
    id: 19,
    name: 'Pro CASEIN PROTEIN',
    description: 'Caseína micelar con 25g de proteína por servicio y liberación prolongada durante 8 horas',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: '/ofertaDelDia3.webp',
    rating: 4.5,
    reviews: 275,
    badge: 'NOCTURNO',
    marca: 'Dymatize',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'pro-casein-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Frambuesa'
  },
  {
    id: 20,
    name: 'Lean WHEY PROTEIN',
    description: 'Proteína de suero con 23g por servicio y L-carnitina para apoyo en la definición muscular',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: '/ofertaDelDia2.webp',
    rating: 4.4,
    reviews: 245,
    badge: 'DEFINICIÓN',
    marca: 'Scitec Nutrition',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'lean-whey-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (85%), L-carnitina (1g), extracto de té verde, CLA (ácido linoleico conjugado), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Arándano'
  },
  {
    id: 21,
    name: 'Ultra MASS GAINER',
    description: 'Ganador de peso con 1000 calorías y 45g de proteína por servicio para aumento de masa muscular',
    originalPrice: 69.99,
    offerPrice: 54.99,
    discount: 21,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.3,
    reviews: 230,
    badge: 'VOLUMEN',
    marca: 'Mass Tech',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'ultra-mass-gainer',
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (3g), glutamina (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Piña'
  },
  {
    id: 22,
    name: 'Premium WHEY CONCENTRATE',
    description: 'Concentrado de proteína de suero con 22g por servicio y excelente relación calidad-precio',
    originalPrice: 39.99,
    offerPrice: 29.99,
    discount: 25,
    image: '/ofertaDelDia3.webp',
    rating: 4.2,
    reviews: 320,
    badge: 'ECONÓMICO',
    marca: 'MyProtein',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'premium-whey-concentrate',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (80%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Melón'
  },
  {
    id: 23,
    name: 'Vegan PROTEIN COMPLETE',
    description: 'Proteína vegetal completa con 20g por servicio y perfil completo de aminoácidos',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.3,
    reviews: 210,
    badge: 'VEGANO',
    marca: 'Sunwarrior',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    superOfertas: true,
    slug: 'vegan-protein-complete',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de guisante (40%), proteína de arroz integral (30%), proteína de semillas de calabaza (15%), proteína de cáñamo (10%), mezcla de aminoácidos esenciales (5%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Toffee'
  },
  {
    id: 24,
    name: 'Gold STANDARD WHEY',
    description: 'Proteína de suero premium con 24g por servicio y mezcla de concentrado, aislado e hidrolizado',
    originalPrice: 54.99,
    offerPrice: 44.99,
    discount: 18,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.8,
    reviews: 520,
    badge: 'TOP VENTAS',
    marca: 'Optimum Nutrition',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'gold-standard-whey',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 70%, aislado de proteína de suero de leche 20%, proteína de suero hidrolizada 10%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Brownie'
  },
  {
    id: 25,
    name: 'Combat PROTEIN POWDER',
    description: 'Proteína de liberación en 5 fases con 25g por servicio para nutrición prolongada',
    originalPrice: 56.99,
    offerPrice: 45.99,
    discount: 19,
    image: '/ofertaDelDia3.webp',
    rating: 4.6,
    reviews: 310,
    badge: 'PREMIUM',
    marca: 'MusclePharm',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'combat-protein-powder',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas de 5 fases (concentrado de proteína de suero de leche, aislado de proteína de suero de leche, proteína de suero hidrolizada, caseína micelar, proteína de clara de huevo), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Cheesecake'
  },
  {
    id: 26,
    name: 'Nitro TECH PROTEIN',
    description: 'Fórmula avanzada con 30g de proteína por servicio y creatina para máximo rendimiento',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.7,
    reviews: 340,
    badge: 'RENDIMIENTO',
    marca: 'MuscleTech',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'nitro-tech-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (70%), concentrado de proteína de suero de leche (20%), creatina monohidrato (3g), L-glutamina (2g), BCAA (2g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Manzana'
  },
  {
    id: 27,
    name: 'Syntha-6 PROTEIN MATRIX',
    description: 'Mezcla de proteínas de liberación sostenida con 22g por servicio y delicioso sabor cremoso',
    originalPrice: 52.99,
    offerPrice: 42.99,
    discount: 19,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.5,
    reviews: 290,
    badge: 'SABOR PREMIUM',
    marca: 'BSN',
    tipo: 'Blend Protein',
    colesterol: 'Moderado',
    slug: 'syntha-6-protein-matrix',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, caseína micelar, proteína de leche, proteína de clara de huevo, proteína de suero hidrolizada), MCT (triglicéridos de cadena media), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Canela'
  },
  {
    id: 28,
    name: 'Serious MASS GAINER',
    description: 'Ganador de peso con 1250 calorías y 50g de proteína por servicio para aumento de masa muscular',
    originalPrice: 74.99,
    offerPrice: 59.99,
    discount: 20,
    image: '/ofertaDelDia3.webp',
    rating: 4.4,
    reviews: 280,
    badge: 'VOLUMEN',
    marca: 'Optimum Nutrition',
    tipo: 'Mass Gainer',
    colesterol: 'Moderado',
    slug: 'serious-mass-gainer',
    informacionAlergenos: 'Contiene leche, soja y gluten. Fabricado en instalaciones que también procesan huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Maltodextrina, concentrado de proteína de suero de leche, caseína micelar, avena en polvo, aceite de MCT, creatina monohidrato (5g), glutamina (5g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), complejo vitamínico y mineral, enzimas digestivas (amilasa, proteasa, lipasa).',
    modoDeUso: 'Mezclar 3 cacitos (100g) con 400-500ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Yogurt'
  },
  {
    id: 29,
    name: 'Iso 100 HYDROLYZED',
    description: 'Proteína de suero hidrolizada con 25g por servicio y cero carbohidratos y grasas',
    originalPrice: 64.99,
    offerPrice: 51.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.8,
    reviews: 330,
    badge: 'PREMIUM',
    marca: 'Dymatize',
    tipo: 'Hydrolyzed Protein',
    colesterol: 'Mínimo',
    slug: 'iso-100-hydrolyzed',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de suero hidrolizada (100%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Mora'
  },
  {
    id: 30,
    name: 'Pure WHEY ISOLATE',
    description: 'Aislado de proteína de suero con 27g por servicio y mínimo contenido de lactosa',
    originalPrice: 57.99,
    offerPrice: 45.99,
    discount: 21,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.7,
    reviews: 315,
    badge: 'CALIDAD',
    marca: 'Reflex Nutrition',
    tipo: 'Isolate Protein',
    colesterol: 'Mínimo',
    superOfertas: true,
    slug: 'pure-whey-isolate',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de suero de leche (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína, lactasa).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Pistache'
  },
  {
    id: 31,
    name: 'Micellar CASEIN PROTEIN',
    description: 'Caseína micelar pura con 24g de proteína por servicio y liberación lenta durante 8 horas',
    originalPrice: 54.99,
    offerPrice: 43.99,
    discount: 20,
    image: '/ofertaDelDia3.webp',
    rating: 4.5,
    reviews: 260,
    badge: 'NOCTURNO',
    marca: 'Optimum Nutrition',
    tipo: 'Casein Protein',
    colesterol: 'Bajo',
    slug: 'micellar-casein-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Caseína micelar (98%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 15 segundos o hasta que se disuelva por completo. Tomar preferentemente antes de dormir.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Almendra'
  },
  {
    id: 32,
    name: 'Egg WHITE PROTEIN',
    description: 'Proteína de clara de huevo con 24g por servicio, baja en grasas y de alta calidad biológica',
    originalPrice: 49.99,
    offerPrice: 39.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.3,
    reviews: 220,
    badge: 'NATURAL',
    marca: 'NOW Sports',
    tipo: 'Egg Protein',
    colesterol: 'Mínimo',
    slug: 'egg-white-protein',
    informacionAlergenos: 'Contiene huevo. Fabricado en instalaciones que también procesan leche, soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de clara de huevo en polvo (95%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Banana Split'
  },
  {
    id: 33,
    name: 'Beef PROTEIN ISOLATE',
    description: 'Proteína aislada de carne de vacuno con 25g por servicio, sin lactosa ni gluten',
    originalPrice: 59.99,
    offerPrice: 47.99,
    discount: 20,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.2,
    reviews: 185,
    badge: 'SIN LACTOSA',
    marca: 'MuscleMeds',
    tipo: 'Beef Protein',
    colesterol: 'Bajo',
    slug: 'beef-protein-isolate',
    informacionAlergenos: 'No contiene lactosa ni gluten. Fabricado en instalaciones que también procesan soja, huevo, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de carne de vacuno (90%), creatina monohidrato (3g), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Chicozapote'
  },
  {
    id: 34,
    name: 'Slim DIET PROTEIN',
    description: 'Proteína para control de peso con 20g por servicio y extractos de plantas para apoyo metabólico',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: '/ofertaDelDia3.webp',
    rating: 4.1,
    reviews: 195,
    badge: 'CONTROL PESO',
    marca: 'PhD Nutrition',
    tipo: 'Diet Protein',
    colesterol: 'Bajo',
    slug: 'slim-diet-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche, caseína micelar), L-carnitina (1g), extracto de té verde, extracto de garcinia cambogia, extracto de café verde, fibra de avena, aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Mamey'
  },
  {
    id: 35,
    name: 'Tri-Blend PROTEIN',
    description: 'Mezcla de tres proteínas con 23g por servicio y liberación en tres fases para nutrición continua',
    originalPrice: 51.99,
    offerPrice: 41.99,
    discount: 19,
    image: '/ofertaDelDia2.webp',
    rating: 4.5,
    reviews: 275,
    badge: 'COMPLETO',
    marca: 'MyProtein',
    tipo: 'Blend Protein',
    colesterol: 'Bajo',
    slug: 'tri-blend-protein',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Mezcla de proteínas (concentrado de proteína de suero de leche 40%, aislado de proteína de suero de leche 30%, caseína micelar 30%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Rompope'
  },
  {
    id: 36,
    name: 'Whey PROTEIN CONCENTRATE',
    description: 'Concentrado de proteína de suero con 22g por servicio y excelente relación calidad-precio',
    originalPrice: 42.99,
    offerPrice: 32.99,
    discount: 23,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4.2,
    reviews: 310,
    badge: 'ECONÓMICO',
    marca: 'Bulk Powders',
    tipo: 'Whey Protein',
    colesterol: 'Bajo',
    slug: 'whey-protein-concentrate',
    informacionAlergenos: 'Contiene leche y soja. Fabricado en instalaciones que también procesan huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Concentrado de proteína de suero de leche (80%), aromas, espesantes (goma xantana, goma guar), edulcorantes (sucralosa, acesulfamo K), sal, enzimas digestivas (bromelina, papaína).',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Mazapán'
  },
  {
    id: 37,
    name: 'Pea PROTEIN ISOLATE',
    description: 'Proteína aislada de guisante con 24g por servicio, vegana y de fácil digestión',
    originalPrice: 47.99,
    offerPrice: 37.99,
    discount: 21,
    image: '/ofertaDelDia3.webp',
    rating: 4.3,
    reviews: 230,
    badge: 'VEGANO',
    marca: 'Bulk Powders',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'pea-protein-isolate',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de guisante (90%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Cajeta'
  },
  {
    id: 38,
    name: 'Rice PROTEIN ISOLATE',
    description: 'Proteína aislada de arroz con 22g por servicio, vegana y sin alérgenos comunes',
    originalPrice: 45.99,
    offerPrice: 36.99,
    discount: 20,
    image: '/ofertaDelDia2.webp',
    rating: 4.1,
    reviews: 190,
    badge: 'VEGANO',
    marca: 'Sunwarrior',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'rice-protein-isolate',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de arroz integral (95%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Guayaba'
  },
  {
    id: 39,
    name: 'Hemp PROTEIN POWDER',
    description: 'Proteína de cáñamo con 18g por servicio, rica en ácidos grasos esenciales y fibra',
    originalPrice: 43.99,
    offerPrice: 34.99,
    discount: 20,
    image: 'https://q2qwccah9hqmefmy.public.blob.vercel-storage.com/evoflex-gral-coat-tabs-front-hsn_1-9yP2K8aLQ71nESrj0BClWhMtfZ8ofx.webp',
    rating: 4,
    reviews: 165,
    badge: 'NATURAL',
    marca: 'Manitoba Harvest',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    superOfertas: true,
    slug: 'hemp-protein-powder',
    informacionAlergenos: 'No contiene alérgenos comunes. Apto para veganos. Fabricado en instalaciones que también procesan soja, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Proteína de semillas de cáñamo (100%), sin aditivos ni conservantes.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Tamarindo'
  },
  {
    id: 40,
    name: 'Soy PROTEIN ISOLATE',
    description: 'Proteína aislada de soja con 25g por servicio, vegana y con perfil completo de aminoácidos',
    originalPrice: 44.99,
    offerPrice: 35.99,
    discount: 20,
    image: '/ofertaDelDia3.webp',
    rating: 4.2,
    reviews: 210,
    badge: 'VEGANO',
    marca: 'NOW Sports',
    tipo: 'Vegan Protein',
    colesterol: 'Sin colesterol',
    slug: 'soy-protein-isolate',
    informacionAlergenos: 'Contiene soja. Apto para veganos. Fabricado en instalaciones que también procesan leche, huevo, gluten, frutos secos y cacahuetes.',
    infoIngredientes: 'Aislado de proteína de soja (95%), aromas naturales, espesantes naturales (goma xantana, goma guar), edulcorante natural (stevia), sal marina.',
    modoDeUso: 'Mezclar 1 cacito (30g) con 250-300ml de agua o leche vegetal. Agitar enérgicamente durante 10 segundos o hasta que se disuelva por completo.',
    recomendacionesDeUso: 'Tomar 1-3 veces al día según necesidades proteicas<<<Ideal después del entrenamiento para maximizar la recuperación<<<Puede tomarse entre comidas como snack proteico<<<Conservar en lugar fresco y seco',
    sabores: 'Chamoy'
  }
]
const stock = [
  { product_id: 1, sabor: 'Chocolate', tamano: '500g', cantidad: 0, precio: 19.99 },
  { product_id: 1, sabor: 'Chocolate', tamano: '1kg', cantidad: 30, precio: 37.98 },
  { product_id: 1, sabor: 'Chocolate', tamano: '2kg', cantidad: 0, precio: 69.97 },
  { product_id: 1, sabor: 'Chocolate', tamano: '5kg', cantidad: 10, precio: 149.93 },
  { product_id: 1, sabor: 'Vainilla', tamano: '500g', cantidad: 0, precio: 19.99 },
  { product_id: 1, sabor: 'Vainilla', tamano: '1kg', cantidad: 0, precio: 37.98 },
  { product_id: 1, sabor: 'Vainilla', tamano: '2kg', cantidad: 20, precio: 69.97 },
  { product_id: 1, sabor: 'Vainilla', tamano: '5kg', cantidad: 0, precio: 149.93 },
  { product_id: 1, sabor: 'Fresa', tamano: '500g', cantidad: 0, precio: 19.99 },
  { product_id: 1, sabor: 'Fresa', tamano: '1kg', cantidad: 30, precio: 37.98 },
  { product_id: 1, sabor: 'Fresa', tamano: '2kg', cantidad: 20, precio: 69.97 },
  { product_id: 1, sabor: 'Fresa', tamano: '5kg', cantidad: 10, precio: 149.93 },
  { product_id: 2, sabor: 'Cookies & Cream', tamano: '500g', cantidad: 15, precio: 22.99 },
  { product_id: 2, sabor: 'Cookies & Cream', tamano: '1kg', cantidad: 12, precio: 43.68 },
  { product_id: 2, sabor: 'Cookies & Cream', tamano: '2kg', cantidad: 5, precio: 80.47 },
  { product_id: 2, sabor: 'Plátano', tamano: '500g', cantidad: 10, precio: 22.99 },
  { product_id: 2, sabor: 'Plátano', tamano: '1kg', cantidad: 18, precio: 43.68 },
  { product_id: 2, sabor: 'Plátano', tamano: '2kg', cantidad: 7, precio: 80.47 },
  { product_id: 2, sabor: 'Plátano', tamano: '5kg', cantidad: 3, precio: 172.43 },
  { product_id: 3, sabor: 'Menta', tamano: '500g', cantidad: 22, precio: 24.99 },
  { product_id: 3, sabor: 'Menta', tamano: '1kg', cantidad: 15, precio: 47.48 },
  { product_id: 3, sabor: 'Menta', tamano: '2kg', cantidad: 8, precio: 87.47 },
  { product_id: 4, sabor: 'Caramelo', tamano: '500g', cantidad: 17, precio: 18.99 },
  { product_id: 4, sabor: 'Caramelo', tamano: '1kg', cantidad: 12, precio: 36.08 },
  { product_id: 5, sabor: 'Café', tamano: '500g', cantidad: 20, precio: 17.99 },
  { product_id: 5, sabor: 'Café', tamano: '1kg', cantidad: 15, precio: 34.18 },
  { product_id: 6, sabor: 'Limón', tamano: '500g', cantidad: 14, precio: 21.99 },
  { product_id: 6, sabor: 'Limón', tamano: '1kg', cantidad: 9, precio: 41.78 },
  { product_id: 7, sabor: 'Coco', tamano: '500g', cantidad: 18, precio: 15.99 },
  { product_id: 7, sabor: 'Coco', tamano: '1kg', cantidad: 13, precio: 30.38 },
  { product_id: 8, sabor: 'Pistacho', tamano: '1kg', cantidad: 11, precio: 32.28 },
  { product_id: 8, sabor: 'Pistacho', tamano: '2kg', cantidad: 6, precio: 59.47 },
  { product_id: 9, sabor: 'Nuez', tamano: '500g', cantidad: 16, precio: 20.99 },
  { product_id: 9, sabor: 'Nuez', tamano: '1kg', cantidad: 12, precio: 39.88 },
  { product_id: 10, sabor: 'Dulce de Leche', tamano: '500g', cantidad: 19, precio: 2.49 },
  { product_id: 10, sabor: 'Dulce de Leche', tamano: '1kg', cantidad: 14, precio: 4.73 },
  { product_id: 11, sabor: 'Mango', tamano: '500g', cantidad: 21, precio: 25.99 },
  { product_id: 11, sabor: 'Mango', tamano: '1kg', cantidad: 16, precio: 49.38 },
  { product_id: 12, sabor: 'Maracuyá', tamano: '500g', cantidad: 13, precio: 29.99 },
  { product_id: 12, sabor: 'Maracuyá', tamano: '1kg', cantidad: 8, precio: 56.98 },
  { product_id: 13, sabor: 'Cereza', tamano: '500g', cantidad: 17, precio: 27.99 },
  { product_id: 13, sabor: 'Cereza', tamano: '1kg', cantidad: 12, precio: 53.18 },
  { product_id: 13, sabor: 'Cereza', tamano: '2kg', cantidad: 7, precio: 97.97 },
  { product_id: 14, sabor: 'Avellana', tamano: '500g', cantidad: 15, precio: 19.99 },
  { product_id: 14, sabor: 'Avellana', tamano: '1kg', cantidad: 10, precio: 37.98 },
  { product_id: 15, sabor: 'Tiramisú', tamano: '500g', cantidad: 18, precio: 26.99 },
  { product_id: 15, sabor: 'Tiramisú', tamano: '1kg', cantidad: 13, precio: 51.28 },
  { product_id: 16, sabor: 'Chicle', tamano: '500g', cantidad: 20, precio: 32.99 },
  { product_id: 17, sabor: 'Sandía', tamano: '500g', cantidad: 14, precio: 18.99 },
  { product_id: 17, sabor: 'Sandía', tamano: '1kg', cantidad: 9, precio: 36.08 },
  { product_id: 18, sabor: 'Kiwi', tamano: '500g', cantidad: 16, precio: 22.99 },
  { product_id: 18, sabor: 'Kiwi', tamano: '1kg', cantidad: 11, precio: 43.68 },
  { product_id: 19, sabor: 'Frambuesa', tamano: '500g', cantidad: 19, precio: 24.99 },
  { product_id: 19, sabor: 'Frambuesa', tamano: '1kg', cantidad: 14, precio: 47.48 },
  { product_id: 20, sabor: 'Arándano', tamano: '500g', cantidad: 17, precio: 21.99 },
  { product_id: 20, sabor: 'Arándano', tamano: '1kg', cantidad: 12, precio: 41.78 },
  { product_id: 21, sabor: 'Piña', tamano: '500g', cantidad: 15, precio: 17.99 },
  { product_id: 21, sabor: 'Piña', tamano: '1kg', cantidad: 10, precio: 34.18 },
  { product_id: 22, sabor: 'Melón', tamano: '500g', cantidad: 13, precio: 16.99 },
  { product_id: 23, sabor: 'Toffee', tamano: '500g', cantidad: 18, precio: 23.99 },
  { product_id: 23, sabor: 'Toffee', tamano: '1kg', cantidad: 13, precio: 45.58 },
  { product_id: 24, sabor: 'Brownie', tamano: '500g', cantidad: 20, precio: 28.99 },
  { product_id: 24, sabor: 'Brownie', tamano: '1kg', cantidad: 15, precio: 55.08 },
  { product_id: 25, sabor: 'Cheesecake', tamano: '500g', cantidad: 16, precio: 26.99 },
  { product_id: 25, sabor: 'Cheesecake', tamano: '1kg', cantidad: 11, precio: 51.28 },
  { product_id: 26, sabor: 'Manzana', tamano: '500g', cantidad: 14, precio: 19.99 },
  { product_id: 27, sabor: 'Canela', tamano: '500g', cantidad: 17, precio: 21.99 },
  { product_id: 27, sabor: 'Canela', tamano: '1kg', cantidad: 12, precio: 41.78 },
  { product_id: 28, sabor: 'Yogurt', tamano: '500g', cantidad: 19, precio: 24.99 },
  { product_id: 28, sabor: 'Yogurt', tamano: '1kg', cantidad: 14, precio: 47.48 },
  { product_id: 29, sabor: 'Mora', tamano: '500g', cantidad: 15, precio: 18.99 },
  { product_id: 30, sabor: 'Pistache', tamano: '500g', cantidad: 18, precio: 27.99 },
  { product_id: 30, sabor: 'Pistache', tamano: '1kg', cantidad: 13, precio: 53.18 },
  { product_id: 31, sabor: 'Almendra', tamano: '500g', cantidad: 16, precio: 25.99 },
  { product_id: 31, sabor: 'Almendra', tamano: '1kg', cantidad: 11, precio: 49.38 },
  { product_id: 32, sabor: 'Banana Split', tamano: '500g', cantidad: 19, precio: 22.99 },
  { product_id: 32, sabor: 'Banana Split', tamano: '1kg', cantidad: 14, precio: 43.68 },
  { product_id: 33, sabor: 'Chicozapote', tamano: '500g', cantidad: 12, precio: 17.99 },
  { product_id: 34, sabor: 'Mamey', tamano: '500g', cantidad: 15, precio: 19.99 },
  { product_id: 34, sabor: 'Mamey', tamano: '1kg', cantidad: 10, precio: 37.98 },
  { product_id: 35, sabor: 'Rompope', tamano: '500g', cantidad: 17, precio: 23.99 },
  { product_id: 35, sabor: 'Rompope', tamano: '1kg', cantidad: 12, precio: 45.58 },
  { product_id: 36, sabor: 'Mazapán', tamano: '500g', cantidad: 20, precio: 26.99 },
  { product_id: 36, sabor: 'Mazapán', tamano: '1kg', cantidad: 15, precio: 51.28 },
  { product_id: 37, sabor: 'Cajeta', tamano: '500g', cantidad: 18, precio: 24.99 },
  { product_id: 37, sabor: 'Cajeta', tamano: '1kg', cantidad: 13, precio: 47.48 },
  { product_id: 38, sabor: 'Guayaba', tamano: '500g', cantidad: 14, precio: 18.99 },
  { product_id: 39, sabor: 'Tamarindo', tamano: '500g', cantidad: 16, precio: 21.99 },
  { product_id: 39, sabor: 'Tamarindo', tamano: '1kg', cantidad: 11, precio: 41.78 },
  { product_id: 40, sabor: 'Chamoy', tamano: '500g', cantidad: 19, precio: 25.99 },
  { product_id: 40, sabor: 'Chamoy', tamano: '1kg', cantidad: 14, precio: 49.38 }
];

const informacionNutricional = [
  {
    product_id: 1,
    porcion: '30g',
    calorias: '120 kcal',
    proteinas: '24g',
    carbohidratos: '3g',
    azucares: '1.5g',
    grasas: '1.8g',
    grasasSaturadas: '1.1g',
    fibra: '0.6g',
    sal: '0.25g',
    sodio: '100mg',
    calcio: '140mg',
    hierro: '1.2mg',
    vitaminaD: '0.75µg',
    vitaminaB12: '1.1µg',
    enzimasDigestivas: '25mg',
    aminoacidos: 'leucina: 2.5g;isoleucina: 1.5g;valina: 1.6g;glutamina: 4.8g'
  },
  {
    product_id: 2,
    porcion: '35g',
    calorias: '135 kcal',
    proteinas: '26g',
    carbohidratos: '4g',
    azucares: '1.8g',
    grasas: '2.0g',
    grasasSaturadas: '1.2g',
    fibra: '0.7g',
    sal: '0.28g',
    sodio: '110mg',
    calcio: '150mg',
    hierro: '1.3mg',
    vitaminaD: '0.8µg',
    vitaminaB12: '1.2µg',
    enzimasDigestivas: '28mg',
    aminoacidos: 'leucina: 2.7g;isoleucina: 1.6g;valina: 1.7g;glutamina: 5.0g'
  },
  {
    product_id: 3,
    porcion: '28g',
    calorias: '110 kcal',
    proteinas: '22g',
    carbohidratos: '2.5g',
    azucares: '1.2g',
    grasas: '1.5g',
    grasasSaturadas: '0.9g',
    fibra: '0.5g',
    sal: '0.22g',
    sodio: '90mg',
    calcio: '130mg',
    hierro: '1.1mg',
    vitaminaD: '0.7µg',
    vitaminaB12: '1.0µg',
    enzimasDigestivas: '22mg',
    aminoacidos: 'leucina: 2.3g;isoleucina: 1.4g;valina: 1.5g;glutamina: 4.5g'
  },
  {
    product_id: 4,
    porcion: '32g',
    calorias: '125 kcal',
    proteinas: '25g',
    carbohidratos: '3.2g',
    azucares: '1.6g',
    grasas: '1.9g',
    grasasSaturadas: '1.2g',
    fibra: '0.65g',
    sal: '0.26g',
    sodio: '105mg',
    calcio: '145mg',
    hierro: '1.25mg',
    vitaminaD: '0.78µg',
    vitaminaB12: '1.15µg',
    enzimasDigestivas: '26mg',
    aminoacidos: 'leucina: 2.6g;isoleucina: 1.55g;valina: 1.65g;glutamina: 4.9g'
  },
  {
    product_id: 5,
    porcion: '25g',
    calorias: '100 kcal',
    proteinas: '20g',
    carbohidratos: '2.2g',
    azucares: '1.0g',
    grasas: '1.3g',
    grasasSaturadas: '0.8g',
    fibra: '0.45g',
    sal: '0.2g',
    sodio: '85mg',
    calcio: '120mg',
    hierro: '1.0mg',
    vitaminaD: '0.65µg',
    vitaminaB12: '0.9µg',
    enzimasDigestivas: '20mg',
    aminoacidos: 'leucina: 2.1g;isoleucina: 1.3g;valina: 1.4g;glutamina: 4.2g'
  },
  {
    product_id: 6,
    porcion: '40g',
    calorias: '150 kcal',
    proteinas: '30g',
    carbohidratos: '5g',
    azucares: '2.0g',
    grasas: '2.2g',
    grasasSaturadas: '1.3g',
    fibra: '0.8g',
    sal: '0.3g',
    sodio: '120mg',
    calcio: '160mg',
    hierro: '1.4mg',
    vitaminaD: '0.85µg',
    vitaminaB12: '1.3µg',
    enzimasDigestivas: '30mg',
    aminoacidos: 'leucina: 3.0g;isoleucina: 1.8g;valina: 1.9g;glutamina: 5.5g'
  },
  {
    product_id: 7,
    porcion: '33g',
    calorias: '130 kcal',
    proteinas: '26g',
    carbohidratos: '3.5g',
    azucares: '1.7g',
    grasas: '1.9g',
    grasasSaturadas: '1.15g',
    fibra: '0.68g',
    sal: '0.27g',
    sodio: '108mg',
    calcio: '148mg',
    hierro: '1.28mg',
    vitaminaD: '0.79µg',
    vitaminaB12: '1.18µg',
    enzimasDigestivas: '27mg',
    aminoacidos: 'leucina: 2.65g;isoleucina: 1.58g;valina: 1.68g;glutamina: 5.0g'
  },
  {
    product_id: 8,
    porcion: '27g',
    calorias: '105 kcal',
    proteinas: '21g',
    carbohidratos: '2.3g',
    azucares: '1.1g',
    grasas: '1.4g',
    grasasSaturadas: '0.85g',
    fibra: '0.48g',
    sal: '0.21g',
    sodio: '88mg',
    calcio: '125mg',
    hierro: '1.05mg',
    vitaminaD: '0.68µg',
    vitaminaB12: '0.95µg',
    enzimasDigestivas: '21mg',
    aminoacidos: 'leucina: 2.2g;isoleucina: 1.35g;valina: 1.45g;glutamina: 4.3g'
  },
  {
    product_id: 9,
    porcion: '38g',
    calorias: '145 kcal',
    proteinas: '29g',
    carbohidratos: '4.5g',
    azucares: '1.9g',
    grasas: '2.1g',
    grasasSaturadas: '1.25g',
    fibra: '0.75g',
    sal: '0.29g',
    sodio: '115mg',
    calcio: '155mg',
    hierro: '1.35mg',
    vitaminaD: '0.82µg',
    vitaminaB12: '1.25µg',
    enzimasDigestivas: '29mg',
    aminoacidos: 'leucina: 2.9g;isoleucina: 1.75g;valina: 1.85g;glutamina: 5.3g'
  },
  {
    product_id: 10,
    porcion: '31g',
    calorias: '122 kcal',
    proteinas: '24.5g',
    carbohidratos: '3.1g',
    azucares: '1.55g',
    grasas: '1.85g',
    grasasSaturadas: '1.12g',
    fibra: '0.62g',
    sal: '0.255g',
    sodio: '102mg',
    calcio: '142mg',
    hierro: '1.22mg',
    vitaminaD: '0.76µg',
    vitaminaB12: '1.12µg',
    enzimasDigestivas: '25.5mg',
    aminoacidos: 'leucina: 2.55g;isoleucina: 1.52g;valina: 1.62g;glutamina: 4.85g'
  },
  {
    product_id: 11,
    porcion: '29g',
    calorias: '115 kcal',
    proteinas: '23g',
    carbohidratos: '2.8g',
    azucares: '1.4g',
    grasas: '1.7g',
    grasasSaturadas: '1.0g',
    fibra: '0.58g',
    sal: '0.24g',
    sodio: '95mg',
    calcio: '135mg',
    hierro: '1.15mg',
    vitaminaD: '0.72µg',
    vitaminaB12: '1.05µg',
    enzimasDigestivas: '24mg',
    aminoacidos: 'leucina: 2.4g;isoleucina: 1.45g;valina: 1.55g;glutamina: 4.6g'
  },
  {
    product_id: 12,
    porcion: '36g',
    calorias: '140 kcal',
    proteinas: '28g',
    carbohidratos: '4.2g',
    azucares: '1.85g',
    grasas: '2.05g',
    grasasSaturadas: '1.22g',
    fibra: '0.72g',
    sal: '0.285g',
    sodio: '112mg',
    calcio: '152mg',
    hierro: '1.32mg',
    vitaminaD: '0.81µg',
    vitaminaB12: '1.22µg',
    enzimasDigestivas: '28.5mg',
    aminoacidos: 'leucina: 2.85g;isoleucina: 1.7g;valina: 1.8g;glutamina: 5.2g'
  },
  {
    product_id: 13,
    porcion: '26g',
    calorias: '102 kcal',
    proteinas: '20.5g',
    carbohidratos: '2.25g',
    azucares: '1.05g',
    grasas: '1.35g',
    grasasSaturadas: '0.82g',
    fibra: '0.46g',
    sal: '0.205g',
    sodio: '86mg',
    calcio: '122mg',
    hierro: '1.02mg',
    vitaminaD: '0.66µg',
    vitaminaB12: '0.92µg',
    enzimasDigestivas: '20.5mg',
    aminoacidos: 'leucina: 2.15g;isoleucina: 1.32g;valina: 1.42g;glutamina: 4.25g'
  },
  {
    product_id: 14,
    porcion: '34g',
    calorias: '132 kcal',
    proteinas: '26.5g',
    carbohidratos: '3.6g',
    azucares: '1.75g',
    grasas: '1.95g',
    grasasSaturadas: '1.18g',
    fibra: '0.69g',
    sal: '0.275g',
    sodio: '109mg',
    calcio: '149mg',
    hierro: '1.29mg',
    vitaminaD: '0.8µg',
    vitaminaB12: '1.19µg',
    enzimasDigestivas: '27.5mg',
    aminoacidos: 'leucina: 2.7g;isoleucina: 1.6g;valina: 1.7g;glutamina: 5.1g'
  },
  {
    product_id: 15,
    porcion: '42g',
    calorias: '155 kcal',
    proteinas: '31g',
    carbohidratos: '5.2g',
    azucares: '2.1g',
    grasas: '2.3g',
    grasasSaturadas: '1.35g',
    fibra: '0.82g',
    sal: '0.31g',
    sodio: '125mg',
    calcio: '165mg',
    hierro: '1.45mg',
    vitaminaD: '0.88µg',
    vitaminaB12: '1.35µg',
    enzimasDigestivas: '31mg',
    aminoacidos: 'leucina: 3.1g;isoleucina: 1.85g;valina: 1.95g;glutamina: 5.7g'
  },
  {
    product_id: 16,
    porcion: '30.5g',
    calorias: '121 kcal',
    proteinas: '24.2g',
    carbohidratos: '3.05g',
    azucares: '1.52g',
    grasas: '1.82g',
    grasasSaturadas: '1.11g',
    fibra: '0.61g',
    sal: '0.252g',
    sodio: '101mg',
    calcio: '141mg',
    hierro: '1.21mg',
    vitaminaD: '0.755µg',
    vitaminaB12: '1.11µg',
    enzimasDigestivas: '25.2mg',
    aminoacidos: 'leucina: 2.52g;isoleucina: 1.51g;valina: 1.61g;glutamina: 4.82g'
  },
  {
    product_id: 17,
    porcion: '37g',
    calorias: '142 kcal',
    proteinas: '28.5g',
    carbohidratos: '4.3g',
    azucares: '1.88g',
    grasas: '2.08g',
    grasasSaturadas: '1.24g',
    fibra: '0.73g',
    sal: '0.288g',
    sodio: '113mg',
    calcio: '153mg',
    hierro: '1.33mg',
    vitaminaD: '0.815µg',
    vitaminaB12: '1.23µg',
    enzimasDigestivas: '28.8mg',
    aminoacidos: 'leucina: 2.88g;isoleucina: 1.72g;valina: 1.82g;glutamina: 5.25g'
  },
  {
    product_id: 18,
    porcion: '28.5g',
    calorias: '112 kcal',
    proteinas: '22.5g',
    carbohidratos: '2.65g',
    azucares: '1.32g',
    grasas: '1.65g',
    grasasSaturadas: '0.98g',
    fibra: '0.55g',
    sal: '0.235g',
    sodio: '93mg',
    calcio: '133mg',
    hierro: '1.13mg',
    vitaminaD: '0.71µg',
    vitaminaB12: '1.03µg',
    enzimasDigestivas: '23.5mg',
    aminoacidos: 'leucina: 2.35g;isoleucina: 1.42g;valina: 1.52g;glutamina: 4.55g'
  },
  {
    product_id: 19,
    porcion: '39g',
    calorias: '148 kcal',
    proteinas: '29.5g',
    carbohidratos: '4.7g',
    azucares: '1.95g',
    grasas: '2.15g',
    grasasSaturadas: '1.28g',
    fibra: '0.77g',
    sal: '0.295g',
    sodio: '118mg',
    calcio: '158mg',
    hierro: '1.38mg',
    vitaminaD: '0.84µg',
    vitaminaB12: '1.28µg',
    enzimasDigestivas: '29.5mg',
    aminoacidos: 'leucina: 2.95g;isoleucina: 1.78g;valina: 1.88g;glutamina: 5.4g'
  },
  {
    product_id: 20,
    porcion: '32.5g',
    calorias: '127 kcal',
    proteinas: '25.5g',
    carbohidratos: '3.35g',
    azucares: '1.65g',
    grasas: '1.92g',
    grasasSaturadas: '1.16g',
    fibra: '0.66g',
    sal: '0.265g',
    sodio: '106mg',
    calcio: '146mg',
    hierro: '1.26mg',
    vitaminaD: '0.775µg',
    vitaminaB12: '1.16µg',
    enzimasDigestivas: '26.5mg',
    aminoacidos: 'leucina: 2.62g;isoleucina: 1.56g;valina: 1.66g;glutamina: 4.95g'
  },
  {
    product_id: 21,
    porcion: '24g',
    calorias: '95 kcal',
    proteinas: '19g',
    carbohidratos: '2.1g',
    azucares: '0.95g',
    grasas: '1.25g',
    grasasSaturadas: '0.75g',
    fibra: '0.42g',
    sal: '0.19g',
    sodio: '80mg',
    calcio: '115mg',
    hierro: '0.95mg',
    vitaminaD: '0.62µg',
    vitaminaB12: '0.85µg',
    enzimasDigestivas: '19mg',
    aminoacidos: 'leucina: 2.0g;isoleucina: 1.25g;valina: 1.35g;glutamina: 4.0g'
  },
  {
    product_id: 22,
    porcion: '41g',
    calorias: '152 kcal',
    proteinas: '30.5g',
    carbohidratos: '5.1g',
    azucares: '2.05g',
    grasas: '2.25g',
    grasasSaturadas: '1.32g',
    fibra: '0.81g',
    sal: '0.305g',
    sodio: '122mg',
    calcio: '162mg',
    hierro: '1.42mg',
    vitaminaD: '0.86µg',
    vitaminaB12: '1.32µg',
    enzimasDigestivas: '30.5mg',
    aminoacidos: 'leucina: 3.05g;isoleucina: 1.82g;valina: 1.92g;glutamina: 5.6g'
  },
  {
    product_id: 23,
    porcion: '33.5g',
    calorias: '131 kcal',
    proteinas: '26.2g',
    carbohidratos: '3.45g',
    azucares: '1.72g',
    grasas: '1.93g',
    grasasSaturadas: '1.17g',
    fibra: '0.67g',
    sal: '0.268g',
    sodio: '107mg',
    calcio: '147mg',
    hierro: '1.27mg',
    vitaminaD: '0.78µg',
    vitaminaB12: '1.17µg',
    enzimasDigestivas: '26.8mg',
    aminoacidos: 'leucina: 2.67g;isoleucina: 1.59g;valina: 1.69g;glutamina: 5.02g'
  },
  {
    product_id: 24,
    porcion: '27.5g',
    calorias: '108 kcal',
    proteinas: '21.5g',
    carbohidratos: '2.45g',
    azucares: '1.22g',
    grasas: '1.55g',
    grasasSaturadas: '0.92g',
    fibra: '0.52g',
    sal: '0.225g',
    sodio: '90mg',
    calcio: '128mg',
    hierro: '1.08mg',
    vitaminaD: '0.69µg',
    vitaminaB12: '0.98µg',
    enzimasDigestivas: '22.5mg',
    aminoacidos: 'leucina: 2.25g;isoleucina: 1.38g;valina: 1.48g;glutamina: 4.4g'
  },
  {
    product_id: 25,
    porcion: '35.5g',
    calorias: '137 kcal',
    proteinas: '27g',
    carbohidratos: '3.85g',
    azucares: '1.82g',
    grasas: '2.02g',
    grasasSaturadas: '1.21g',
    fibra: '0.71g',
    sal: '0.282g',
    sodio: '111mg',
    calcio: '151mg',
    hierro: '1.31mg',
    vitaminaD: '0.805µg',
    vitaminaB12: '1.21µg',
    enzimasDigestivas: '28.2mg',
    aminoacidos: 'leucina: 2.78g;isoleucina: 1.65g;valina: 1.75g;glutamina: 5.15g'
  },
  {
    product_id: 26,
    porcion: '29.5g',
    calorias: '117 kcal',
    proteinas: '23.5g',
    carbohidratos: '2.85g',
    azucares: '1.42g',
    grasas: '1.72g',
    grasasSaturadas: '1.03g',
    fibra: '0.59g',
    sal: '0.242g',
    sodio: '96mg',
    calcio: '136mg',
    hierro: '1.16mg',
    vitaminaD: '0.725µg',
    vitaminaB12: '1.06µg',
    enzimasDigestivas: '24.2mg',
    aminoacidos: 'leucina: 2.42g;isoleucina: 1.46g;valina: 1.56g;glutamina: 4.65g'
  },
  {
    product_id: 27,
    porcion: '38.5g',
    calorias: '146 kcal',
    proteinas: '29.2g',
    carbohidratos: '4.6g',
    azucares: '1.92g',
    grasas: '2.12g',
    grasasSaturadas: '1.26g',
    fibra: '0.76g',
    sal: '0.292g',
    sodio: '116mg',
    calcio: '156mg',
    hierro: '1.36mg',
    vitaminaD: '0.83µg',
    vitaminaB12: '1.26µg',
    enzimasDigestivas: '29.2mg',
    aminoacidos: 'leucina: 2.92g;isoleucina: 1.76g;valina: 1.86g;glutamina: 5.35g'
  },
  {
    product_id: 28,
    porcion: '31.5g',
    calorias: '124 kcal',
    proteinas: '24.8g',
    carbohidratos: '3.25g',
    azucares: '1.58g',
    grasas: '1.88g',
    grasasSaturadas: '1.13g',
    fibra: '0.63g',
    sal: '0.258g',
    sodio: '103mg',
    calcio: '143mg',
    hierro: '1.23mg',
    vitaminaD: '0.765µg',
    vitaminaB12: '1.13µg',
    enzimasDigestivas: '25.8mg',
    aminoacidos: 'leucina: 2.58g;isoleucina: 1.54g;valina: 1.64g;glutamina: 4.88g'
  },
  {
    product_id: 29,
    porcion: '26.5g',
    calorias: '104 kcal',
    proteinas: '21g',
    carbohidratos: '2.35g',
    azucares: '1.15g',
    grasas: '1.45g',
    grasasSaturadas: '0.87g',
    fibra: '0.49g',
    sal: '0.215g',
    sodio: '89mg',
    calcio: '126mg',
    hierro: '1.06mg',
    vitaminaD: '0.675µg',
    vitaminaB12: '0.96µg',
    enzimasDigestivas: '21.5mg',
    aminoacidos: 'leucina: 2.18g;isoleucina: 1.34g;valina: 1.44g;glutamina: 4.32g'
  },
  {
    product_id: 30,
    porcion: '36.5g',
    calorias: '141 kcal',
    proteinas: '28.2g',
    carbohidratos: '4.25g',
    azucares: '1.86g',
    grasas: '2.06g',
    grasasSaturadas: '1.23g',
    fibra: '0.725g',
    sal: '0.286g',
    sodio: '113mg',
    calcio: '153mg',
    hierro: '1.33mg',
    vitaminaD: '0.812µg',
    vitaminaB12: '1.23µg',
    enzimasDigestivas: '28.6mg',
    aminoacidos: 'leucina: 2.86g;isoleucina: 1.71g;valina: 1.81g;glutamina: 5.22g'
  },
  {
    product_id: 31,
    porcion: '34.5g',
    calorias: '134 kcal',
    proteinas: '26.8g',
    carbohidratos: '3.65g',
    azucares: '1.78g',
    grasas: '1.98g',
    grasasSaturadas: '1.19g',
    fibra: '0.7g',
    sal: '0.278g',
    sodio: '110mg',
    calcio: '150mg',
    hierro: '1.3mg',
    vitaminaD: '0.802µg',
    vitaminaB12: '1.2µg',
    enzimasDigestivas: '27.8mg',
    aminoacidos: 'leucina: 2.75g;isoleucina: 1.64g;valina: 1.74g;glutamina: 5.12g'
  },
  {
    product_id: 32,
    porcion: '28.2g',
    calorias: '111 kcal',
    proteinas: '22.2g',
    carbohidratos: '2.62g',
    azucares: '1.3g',
    grasas: '1.62g',
    grasasSaturadas: '0.97g',
    fibra: '0.54g',
    sal: '0.232g',
    sodio: '92mg',
    calcio: '132mg',
    hierro: '1.12mg',
    vitaminaD: '0.705µg',
    vitaminaB12: '1.02µg',
    enzimasDigestivas: '23.2mg',
    aminoacidos: 'leucina: 2.32g;isoleucina: 1.41g;valina: 1.51g;glutamina: 4.52g'
  },
  {
    product_id: 33,
    porcion: '39.5g',
    calorias: '149 kcal',
    proteinas: '29.8g',
    carbohidratos: '4.75g',
    azucares: '1.98g',
    grasas: '2.18g',
    grasasSaturadas: '1.29g',
    fibra: '0.78g',
    sal: '0.298g',
    sodio: '119mg',
    calcio: '159mg',
    hierro: '1.39mg',
    vitaminaD: '0.845µg',
    vitaminaB12: '1.29µg',
    enzimasDigestivas: '29.8mg',
    aminoacidos: 'leucina: 2.98g;isoleucina: 1.79g;valina: 1.89g;glutamina: 5.45g'
  },
  {
    product_id: 34,
    porcion: '32.8g',
    calorias: '128 kcal',
    proteinas: '25.8g',
    carbohidratos: '3.38g',
    azucares: '1.68g',
    grasas: '1.94g',
    grasasSaturadas: '1.17g',
    fibra: '0.67g',
    sal: '0.268g',
    sodio: '107mg',
    calcio: '147mg',
    hierro: '1.27mg',
    vitaminaD: '0.782µg',
    vitaminaB12: '1.17µg',
    enzimasDigestivas: '26.8mg',
    aminoacidos: 'leucina: 2.64g;isoleucina: 1.57g;valina: 1.67g;glutamina: 4.98g'
  },
  {
    product_id: 35,
    porcion: '23.5g',
    calorias: '93 kcal',
    proteinas: '18.5g',
    carbohidratos: '2.05g',
    azucares: '0.92g',
    grasas: '1.22g',
    grasasSaturadas: '0.73g',
    fibra: '0.41g',
    sal: '0.185g',
    sodio: '78mg',
    calcio: '112mg',
    hierro: '0.92mg',
    vitaminaD: '0.605µg',
    vitaminaB12: '0.82µg',
    enzimasDigestivas: '18.5mg',
    aminoacidos: 'leucina: 1.95g;isoleucina: 1.22g;valina: 1.32g;glutamina: 3.9g'
  },
  {
    product_id: 36,
    porcion: '40.5g',
    calorias: '153 kcal',
    proteinas: '30.8g',
    carbohidratos: '5.15g',
    azucares: '2.08g',
    grasas: '2.28g',
    grasasSaturadas: '1.34g',
    fibra: '0.815g',
    sal: '0.308g',
    sodio: '123mg',
    calcio: '163mg',
    hierro: '1.43mg',
    vitaminaD: '0.87µg',
    vitaminaB12: '1.33µg',
    enzimasDigestivas: '30.8mg',
    aminoacidos: 'leucina: 3.08g;isoleucina: 1.84g;valina: 1.94g;glutamina: 5.65g'
  },
  {
    product_id: 37,
    porcion: '33.2g',
    calorias: '130 kcal',
    proteinas: '26g',
    carbohidratos: '3.42g',
    azucares: '1.7g',
    grasas: '1.92g',
    grasasSaturadas: '1.16g',
    fibra: '0.665g',
    sal: '0.266g',
    sodio: '106mg',
    calcio: '146mg',
    hierro: '1.26mg',
    vitaminaD: '0.775µg',
    vitaminaB12: '1.16µg',
    enzimasDigestivas: '26.6mg',
    aminoacidos: 'leucina: 2.66g;isoleucina: 1.58g;valina: 1.68g;glutamina: 5.0g'
  },
  {
    product_id: 38,
    porcion: '27.8g',
    calorias: '109 kcal',
    proteinas: '21.8g',
    carbohidratos: '2.58g',
    azucares: '1.28g',
    grasas: '1.58g',
    grasasSaturadas: '0.95g',
    fibra: '0.53g',
    sal: '0.228g',
    sodio: '91mg',
    calcio: '131mg',
    hierro: '1.11mg',
    vitaminaD: '0.695µg',
    vitaminaB12: '1.01µg',
    enzimasDigestivas: '22.8mg',
    aminoacidos: 'leucina: 2.28g;isoleucina: 1.39g;valina: 1.49g;glutamina: 4.48g'
  },
  {
    product_id: 39,
    porcion: '37.5g',
    calorias: '144 kcal',
    proteinas: '28.8g',
    carbohidratos: '4.35g',
    azucares: '1.9g',
    grasas: '2.1g',
    grasasSaturadas: '1.25g',
    fibra: '0.74g',
    sal: '0.29g',
    sodio: '115mg',
    calcio: '155mg',
    hierro: '1.35mg',
    vitaminaD: '0.825µg',
    vitaminaB12: '1.25µg',
    enzimasDigestivas: '29mg',
    aminoacidos: 'leucina: 2.9g;isoleucina: 1.74g;valina: 1.84g;glutamina: 5.3g'
  },
  {
    product_id: 40,
    porcion: '30.8g',
    calorias: '122 kcal',
    proteinas: '24.5g',
    carbohidratos: '3.08g',
    azucares: '1.54g',
    grasas: '1.84g',
    grasasSaturadas: '1.11g',
    fibra: '0.615g',
    sal: '0.254g',
    sodio: '101mg',
    calcio: '141mg',
    hierro: '1.21mg',
    vitaminaD: '0.755µg',
    vitaminaB12: '1.11µg',
    enzimasDigestivas: '25.4mg',
    aminoacidos: 'leucina: 2.54g;isoleucina: 1.52g;valina: 1.62g;glutamina: 4.84g'
  }
];
export function sacarStock(id){
  const stockProductoElegido = stock.filter(item => item.product_id === id);
  if(!stockProductoElegido){
    return null
  }
  return stockProductoElegido
}
export function sacarInformacionNutricional(id){
  const informacionNutricionalProductoElegido = informacionNutricional.filter(item => item.product_id === id);
  if(!informacionNutricionalProductoElegido){
    return null
  }
  return informacionNutricionalProductoElegido
}
export const productosSuperOfertas = allProducts.filter(producto => producto.superOfertas);

export function especiales(tituloEspecial) {
  return allProducts.filter((producto) => {
    if (!producto.categoriaEspecial) return false;
    const categorias = producto.categoriaEspecial.split("<<<");
    return categorias.includes(tituloEspecial);
  });
}